apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: eks-dev-slava
  namespace: ${NAMESPACE}
spec:
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: ${NAMESPACE}
    publicIP: true
    region: us-east-2
    worker:
      instanceType: t3.small
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
    workersNumber: 1
    sshKeyName: ${AWS_SSH_KEY_NAME}
  template: aws-eks-0-0-1
  credential: "aws-cluster-identity-cred"
