apiVersion: v2
name: aws-eks
description: |
  An HMC template to deploy a cluster on EKS with bootstrapped control plane nodes.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.2
annotations:
  hmc.mirantis.com/infrastructure-providers: aws
  hmc.mirantis.com/controlplane-providers: eks
  hmc.mirantis.com/bootstrap-providers: eks
